/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./lib/**/*.{js,ts,jsx,tsx}",
    // "./src/**/*.{js,jsx,ts,tsx}",
    "./index.html",
  ],
  theme: {
    colors: {
      backgroundTheme: "#21294C",
      textDarkGray: "#4E4E4E",
      textLightDark: "#4E4E4E",
      textLightGray: "#8D91A3",
      textDark: "#1B2124",
      backgroundLight: "#FFFFFF",
      backgroundDark: "#000000",
      tableBackground: "#0000A",
      tableBorder: "#0000000D",
      borderLight: "#E4E5E9",
      buttonDisabled: "#8D91A3",
      border: "#E4E5E9",
      errorText: "#FD6868",
      disabledPrimaryBtn: "#7F879E",
      disabledSecondaryBtn: "#CCCCCC",
      backgroundLightGreen: "#C8F2E1",
      backgroundDarkGreen: "#22D086",
      backgroundLightRed: "#FFD9D9",
      backgroundDarkRed: "#FD6868",
      backgroundLightYellow: "#FEEAC9",
      backgroundDarkYellow: "#FFAC2A",
      mainBackground: "#FAFAFA",
      backgroundModal: "#000000BF",
    },
    extend: {},
  },
  plugins: [],
};
