import { AnyObject } from "yup";

export const response={
    "message": "",
    "hasError": false,
    "totalRecords": 0,
    "data": [
        {
            "id": 6,
            "parentId": 0,
            "virtualId": 0,
            "name": "Bank Advice",
            "displayName": null,
            "code": "Bank Advice",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 297,
            "parentId": 6,
            "virtualId": 0,
            "name": "Bank Advice Active",
            "displayName": null,
            "code": "bank_advice_jsonn",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 296,
            "parentId": 6,
            "virtualId": 0,
            "name": "Bank Advice Consolidated",
            "displayName": null,
            "code": "bank_advice_json",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 116075,
            "parentId": 2,
            "virtualId": 0,
            "name": "Bulk Mail Template",
            "displayName": null,
            "code": "Bulk_temp",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 28126,
            "parentId": 10,
            "virtualId": 0,
            "name": "Complaince PF",
            "displayName": null,
            "code": "compliance_pf_report",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 22301,
            "parentId": 10,
            "virtualId": 0,
            "name": "Complaince PF Report",
            "displayName": null,
            "code": "Compliamce_PF_Report",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 16844,
            "parentId": 10,
            "virtualId": 0,
            "name": "Complaince PT",
            "displayName": null,
            "code": "Compliance _PT",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 17111,
            "parentId": 10,
            "virtualId": 0,
            "name": "Complaince PT 2",
            "displayName": null,
            "code": "Compliance_PT2",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 104522,
            "parentId": 10,
            "virtualId": 0,
            "name": "Compliance Employee Master",
            "displayName": null,
            "code": "Comp_EMP",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 105111,
            "parentId": 10,
            "virtualId": 0,
            "name": "Compliance ESI Report",
            "displayName": null,
            "code": "comp_ESI_repo",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 123284,
            "parentId": 1,
            "virtualId": 0,
            "name": "Compliance PF Report",
            "displayName": null,
            "code": "comp_pf_repooo",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 10,
            "parentId": 0,
            "virtualId": 0,
            "name": "Compliance Reports",
            "displayName": null,
            "code": "Compliance Reports",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 278,
            "parentId": 4,
            "virtualId": 0,
            "name": "Cost Center",
            "displayName": null,
            "code": "Cost_Center",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 292,
            "parentId": 3,
            "virtualId": 0,
            "name": "CTC Checklist",
            "displayName": null,
            "code": "ctc_checklist",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 3,
            "parentId": 0,
            "virtualId": 0,
            "name": "CTC Reports",
            "displayName": null,
            "code": "CTC Reports",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 281,
            "parentId": 2,
            "virtualId": 0,
            "name": "Employee Master",
            "displayName": null,
            "code": "employee_master",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 282,
            "parentId": 2,
            "virtualId": 0,
            "name": "Employees with PAN",
            "displayName": null,
            "code": "Employees_with_PAN",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 284,
            "parentId": 2,
            "virtualId": 0,
            "name": "Employees with UAN",
            "displayName": null,
            "code": "Employees_with_UAN",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 283,
            "parentId": 2,
            "virtualId": 0,
            "name": "Employees without PAN",
            "displayName": null,
            "code": "Employees_without_PAN",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 285,
            "parentId": 2,
            "virtualId": 0,
            "name": "Employees without UAN",
            "displayName": null,
            "code": "Employees_without_UAN",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 31948,
            "parentId": 8,
            "virtualId": 0,
            "name": "EPS Clarification Report",
            "displayName": null,
            "code": "EPS_Clarification_Report",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 109449,
            "parentId": 10,
            "virtualId": 0,
            "name": "Esewa Report Arrear",
            "displayName": null,
            "code": "ESEVAARR",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 109102,
            "parentId": 10,
            "virtualId": 0,
            "name": "Esewa Report Regular",
            "displayName": null,
            "code": "ESEVA",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 299,
            "parentId": 8,
            "virtualId": 0,
            "name": "ESI",
            "displayName": null,
            "code": "esi_report",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 12079,
            "parentId": 4,
            "virtualId": 0,
            "name": "F & F Reg Arrears",
            "displayName": null,
            "code": "F & F_Reg_Arrears",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 275,
            "parentId": 4,
            "virtualId": 0,
            "name": "F and F Register",
            "displayName": null,
            "code": "F&F_CUSTOMIZED",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 119255,
            "parentId": 1,
            "virtualId": 0,
            "name": "Form16",
            "displayName": null,
            "code": "Form16",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 116852,
            "parentId": 1,
            "virtualId": 0,
            "name": "Form5 Report",
            "displayName": null,
            "code": "FORM5",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 108746,
            "parentId": 7,
            "virtualId": 0,
            "name": "General Codes",
            "displayName": null,
            "code": "GENERALCODES",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 9,
            "parentId": 0,
            "virtualId": 0,
            "name": "Graphs",
            "displayName": null,
            "code": "Graphs",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 109999,
            "parentId": 1,
            "virtualId": 0,
            "name": "Gratuity Report",
            "displayName": null,
            "code": "Gratuity",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 9562,
            "parentId": 9,
            "virtualId": 0,
            "name": "Gross Salary & Net Pay",
            "displayName": null,
            "code": "Gross_Salary_Net Pay",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 289,
            "parentId": 2,
            "virtualId": 0,
            "name": "Head Count",
            "displayName": null,
            "code": "Head_Count",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 9559,
            "parentId": 9,
            "virtualId": 0,
            "name": "Head Count Details",
            "displayName": null,
            "code": "Head_Count_Details",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 288,
            "parentId": 2,
            "virtualId": 0,
            "name": "Hold & Release",
            "displayName": null,
            "code": "Hold_Release",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 280,
            "parentId": 4,
            "virtualId": 0,
            "name": "Hold Salary",
            "displayName": null,
            "code": "Hold_Salary",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 11,
            "parentId": 0,
            "virtualId": 0,
            "name": "Internal",
            "displayName": null,
            "code": "Internal",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 104204,
            "parentId": 7,
            "virtualId": 0,
            "name": "Loan Report",
            "displayName": null,
            "code": "loan_repo",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 7,
            "parentId": 0,
            "virtualId": 0,
            "name": "Loan Reports",
            "displayName": null,
            "code": "Loan Reports",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 111646,
            "parentId": 8,
            "virtualId": 0,
            "name": "LOP Report",
            "displayName": null,
            "code": "LOP_REPORT",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 102735,
            "parentId": 8,
            "virtualId": 0,
            "name": "LWF LocationWise",
            "displayName": null,
            "code": "lwf_location",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 108370,
            "parentId": 8,
            "virtualId": 0,
            "name": "Lwf Report",
            "displayName": null,
            "code": "LWF_new",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 9560,
            "parentId": 9,
            "virtualId": 0,
            "name": "Male/Female Ratio",
            "displayName": null,
            "code": "Male/Female_Ratio",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 103243,
            "parentId": 1,
            "virtualId": 0,
            "name": "Manual Perk",
            "displayName": null,
            "code": "MANUAL_PERK",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 2,
            "parentId": 0,
            "virtualId": 0,
            "name": "Master Reports",
            "displayName": null,
            "code": "Master Reports",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 27352,
            "parentId": 10,
            "virtualId": 0,
            "name": "MC Template",
            "displayName": null,
            "code": "esi_mc",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 290,
            "parentId": 2,
            "virtualId": 0,
            "name": "Missing Bank Account No",
            "displayName": null,
            "code": "Missing Bank_Account No",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 291,
            "parentId": 2,
            "virtualId": 0,
            "name": "Missing Email ID",
            "displayName": null,
            "code": "Missing_Email ID",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 277,
            "parentId": 4,
            "virtualId": 0,
            "name": "Negative Salary",
            "displayName": null,
            "code": "Negative_Salary",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 112163,
            "parentId": 5,
            "virtualId": 0,
            "name": "Netpay Variance report",
            "displayName": null,
            "code": "netpayVariancerepo",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 286,
            "parentId": 2,
            "virtualId": 0,
            "name": "New Joinee",
            "displayName": null,
            "code": "New_Joinee",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 1,
            "parentId": 0,
            "virtualId": 0,
            "name": "Other Reports",
            "displayName": null,
            "code": "Other Reports",
            "isChecked": false,
            "isExpanded": true,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 103114,
            "parentId": 1,
            "virtualId": 0,
            "name": "Perk Report",
            "displayName": null,
            "code": "PRKRPT",
            "isChecked": true,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 120025,
            "parentId": 1,
            "virtualId": 0,
            "name": "Perquisite Report",
            "displayName": null,
            "code": "Perq",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 298,
            "parentId": 8,
            "virtualId": 0,
            "name": "PF Checklist",
            "displayName": null,
            "code": "pf_report",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 102594,
            "parentId": 8,
            "virtualId": 0,
            "name": "PT LocationWise",
            "displayName": null,
            "code": "PT_Loco",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 108069,
            "parentId": 8,
            "virtualId": 0,
            "name": "PT Report",
            "displayName": null,
            "code": "PT_new",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 103321,
            "parentId": 1,
            "virtualId": 0,
            "name": "Reiumbesment Eligibility",
            "displayName": null,
            "code": "Remb_Eligibility",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 287,
            "parentId": 2,
            "virtualId": 0,
            "name": "Resignee",
            "displayName": null,
            "code": "Resignee",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 119640,
            "parentId": 1,
            "virtualId": 0,
            "name": "Salary Annexure",
            "displayName": null,
            "code": "Annexure",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 273,
            "parentId": 4,
            "virtualId": 0,
            "name": "Salary Register Active",
            "displayName": null,
            "code": "salary_register",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 12078,
            "parentId": 4,
            "virtualId": 0,
            "name": "Salary Register Active - Arrears",
            "displayName": null,
            "code": "Salary Register Active _Arrears",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 274,
            "parentId": 4,
            "virtualId": 0,
            "name": "Salary Register Consolidated",
            "displayName": null,
            "code": "SALREGCON",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 4,
            "parentId": 0,
            "virtualId": 0,
            "name": "Salary Reports",
            "displayName": null,
            "code": "Salary Reports",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 295,
            "parentId": 5,
            "virtualId": 0,
            "name": "Salary Variance-CM LM",
            "displayName": null,
            "code": "salary_variance",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 294,
            "parentId": 5,
            "virtualId": 0,
            "name": "Salary Variance-CTC CM",
            "displayName": null,
            "code": "ctc_variance",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 8,
            "parentId": 0,
            "virtualId": 0,
            "name": "Statutory Reports",
            "displayName": null,
            "code": "Statutory Reports",
            "isChecked": false,
            "isExpanded": true,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 9561,
            "parentId": 9,
            "virtualId": 0,
            "name": "Tax Paid Details",
            "displayName": null,
            "code": "",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 102969,
            "parentId": 8,
            "virtualId": 0,
            "name": "Tax Reconciliation",
            "displayName": null,
            "code": "Tax_Reco",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 301,
            "parentId": 8,
            "virtualId": 0,
            "name": "TDS",
            "displayName": null,
            "code": "tds_report",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 279,
            "parentId": 4,
            "virtualId": 0,
            "name": "Variable Pay",
            "displayName": null,
            "code": "Variable_Pay",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 5,
            "parentId": 0,
            "virtualId": 0,
            "name": "Variance Reports",
            "displayName": null,
            "code": "Variance Reports",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        },
        {
            "id": 276,
            "parentId": 4,
            "virtualId": 0,
            "name": "Zero Salary",
            "displayName": null,
            "code": "Zero_Salary",
            "isChecked": false,
            "isExpanded": false,
            "enableBackUp": false,
            "sprite": null,
            "reportTrees": {
                "reportTree": [],
                "reportGroupTree": [],
                "enableBackUp": false,
                "createdById": 0,
                "lastModifiedById": 0,
                "createdDate": null,
                "lastModifiedDate": null,
                "createdByIP": null,
                "lastModifiedByIP": null,
                "recordStatusId": 0,
                "recordStatus": null,
                "errorMessage": null,
                "sqlCommand": 0,
                "totalRecords": 0,
                "pageSize": 0,
                "pageNumber": 0,
                "sortExpression": null,
                "sortDirection": null,
                "sortOrder": 0,
                "slNo": 0
            }
        }
    ]
}

  const initialObj: AnyObject = {};
  export const modifiedData: AnyObject = response.data.reduce((acc, menu) => {
    if (menu?.parentId === 0) {
      if (
        !acc[String(menu?.id)] ||
        (acc[String(menu?.id)] && acc[String(menu?.id)]?.label === "")
      ) {
        acc[String(menu.id)] = {
          value: menu?.id,
          label: menu?.name,
          isChecked: menu?.isChecked,
          isAccordianOpen: menu?.isExpanded,
          isAtleastOneSubMenuSelected: acc[String(menu.id)]
            ?.isAtleastOneSubMenuSelected
            ? acc[String(menu.id)]?.isAtleastOneSubMenuSelected
            : false,
          subMenu: acc[String(menu?.id)]?.subMenu
            ? [...acc[String(menu?.id)].subMenu]
            : [],
        };
      }
    } else {
      if (acc[String(menu?.parentId)]) {
        if (menu.isChecked) {
          acc[String(menu?.parentId)].isAtleastOneSubMenuSelected = true;
        }
        acc[String(menu.parentId)]?.subMenu.push({
          value: menu?.id,
          label: menu?.name,
          isChecked: menu?.isChecked,
        });
      } else {
        acc[String(menu?.parentId)] = {
          value: menu?.parentId,
          label: "",
          isChecked: false,
          isAccordianOpen: false,
          isAtleastOneSubMenuSelected: menu?.isChecked,
          subMenu: [
            {
              value: menu?.id,
              label: menu?.name,
              isChecked: menu?.isChecked,
            },
          ],
        };
      }
    }

    return acc;
  }, initialObj);

//   console.log(modifiedData,'*******');
  