import { AnyObject } from "yup";

export const response2 = {
  message: "",
  hasError: false,
  data: {
    id: 0,
    name: null,
    description: null,
    menuId: 0,
    parentId: 0,
    menuName: null,
    applicationId: 0,
    applicationType: null,
    rolePermissions: [
      {
        id: 0,
        roleId: 0,
        menuId: 10,
        menuName: "Client",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 12,
        menuName: "View",
        parentId: 10,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 14,
        menuName: "Add",
        parentId: 10,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 16,
        menuName: "Modify",
        parentId: 10,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 18,
        menuName: "Delete",
        parentId: 10,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 20,
        menuName: "User",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 22,
        menuName: "View",
        parentId: 20,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 24,
        menuName: "Add",
        parentId: 20,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 26,
        menuName: "Modify",
        parentId: 20,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 28,
        menuName: "Delete",
        parentId: 20,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 30,
        menuName: "Role",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 32,
        menuName: "View",
        parentId: 30,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 34,
        menuName: "Add",
        parentId: 30,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 36,
        menuName: "Modify",
        parentId: 30,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 38,
        menuName: "Delete",
        parentId: 30,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 40,
        menuName: "UrlReferrer",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1000,
        menuName: "Dashboard",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1100,
        menuName: "Configure",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1110,
        menuName: "User Reports",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1112,
        menuName: "View",
        parentId: 1110,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1114,
        menuName: "Add",
        parentId: 1110,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1116,
        menuName: "Modify",
        parentId: 1110,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1118,
        menuName: "Delete",
        parentId: 1110,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1120,
        menuName: "DataSource",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1122,
        menuName: "View",
        parentId: 1120,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1124,
        menuName: "Add",
        parentId: 1120,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1126,
        menuName: "Modify",
        parentId: 1120,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1128,
        menuName: "Delete",
        parentId: 1120,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1130,
        menuName: "Report",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1132,
        menuName: "View",
        parentId: 1130,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1134,
        menuName: "Add",
        parentId: 1130,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1136,
        menuName: "Modify",
        parentId: 1130,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1138,
        menuName: "Delete",
        parentId: 1130,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1140,
        menuName: "Copy",
        parentId: 1130,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1150,
        menuName: "Publish Report",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1152,
        menuName: "View",
        parentId: 1150,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1154,
        menuName: "Add",
        parentId: 1150,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1156,
        menuName: "Modify",
        parentId: 1150,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1158,
        menuName: "Delete",
        parentId: 1150,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1160,
        menuName: "Report Group",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1162,
        menuName: "View",
        parentId: 1160,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1164,
        menuName: "Add",
        parentId: 1160,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1166,
        menuName: "Modify",
        parentId: 1160,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1168,
        menuName: "Delete",
        parentId: 1160,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1180,
        menuName: "Powerpay DB",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2101,
        menuName: "Report Upload",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2103,
        menuName: "View",
        parentId: 2101,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2104,
        menuName: "Upload",
        parentId: 2101,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2105,
        menuName: "Upload Folder",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2106,
        menuName: "View",
        parentId: 2105,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2107,
        menuName: "Map to User",
        parentId: 2105,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2108,
        menuName: "Add",
        parentId: 2105,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2109,
        menuName: "Message",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2112,
        menuName: "Upload File",
        parentId: 2111,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2113,
        menuName: "Add",
        parentId: 2111,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2115,
        menuName: "Add",
        parentId: 2114,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2116,
        menuName: "ReUpload",
        parentId: 2114,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2117,
        menuName: "Utilisation Statistics",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2118,
        menuName: "View",
        parentId: 2117,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2119,
        menuName: "Search",
        parentId: 2117,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2120,
        menuName: "Export",
        parentId: 2117,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2121,
        menuName: " PowerPay Last  Month",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2122,
        menuName: "LookUpData",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2123,
        menuName: "Edit",
        parentId: 2122,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2124,
        menuName: "Email Schedule",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2125,
        menuName: "Save",
        parentId: 2124,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2126,
        menuName: "Restart System",
        parentId: 1100,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2127,
        menuName: "DifferentialReport",
        parentId: 1,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2000,
        menuName: "Dashboard",
        parentId: 2,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2100,
        menuName: "Reports",
        parentId: 2,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2102,
        menuName: "Downloads",
        parentId: 2,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 1,
        menuName: "Admin",
        parentId: 0,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
      {
        id: 0,
        roleId: 0,
        menuId: 2,
        menuName: "Client",
        parentId: 0,
        isCheckedId: false,
        expanded: true,
        createdById: 0,
        lastModifiedById: 0,
        createdDate: null,
        lastModifiedDate: null,
        createdByIP: null,
        lastModifiedByIP: null,
        recordStatusId: 1,
        recordStatus: null,
        errorMessage: null,
        sqlCommand: 0,
        totalRecords: 0,
        pageSize: 0,
        pageNumber: 0,
        sortExpression: null,
        sortDirection: null,
        sortOrder: 0,
        slNo: 0,
      },
    ],
    createdById: 0,
    lastModifiedById: 0,
    createdDate: null,
    lastModifiedDate: null,
    createdByIP: null,
    lastModifiedByIP: null,
    recordStatusId: 0,
    recordStatus: null,
    errorMessage: null,
    sqlCommand: 0,
    totalRecords: 0,
    pageSize: 0,
    pageNumber: 0,
    sortExpression: null,
    sortDirection: null,
    sortOrder: 0,
    slNo: 0,
  },
};

const initialObj: AnyObject = {};
export const modifiedData2: AnyObject = response2.data.rolePermissions.reduce(
  (acc, menu) => {
    if (menu?.parentId === 0) {
      if (
        !acc[String(menu?.menuId)] ||
        (acc[String(menu?.menuId)] && acc[String(menu?.menuId)]?.label === "")
      ) {
        acc[String(menu?.menuId)] = {
          value: menu?.menuId,
          label: menu?.menuName,
          isChecked: menu?.isCheckedId,
          isAccordianOpen: menu?.expanded,
          isAtleastOneSubMenuSelected: acc[String(menu.menuId)]
            ?.isAtleastOneSubMenuSelected
            ? acc[String(menu.menuId)]?.isAtleastOneSubMenuSelected
            : false,
          subMenu: acc[String(menu?.menuId)]?.subMenu
            ? [...acc[String(menu?.menuId)].subMenu]
            : [],
        };
      }
    } else {
      if (acc[String(menu?.parentId)]) {
        if (menu.isCheckedId) {
          acc[String(menu?.parentId)].isAtleastOneSubMenuSelected = true;
        }
        acc[String(menu.parentId)]?.subMenu.push({
          value: menu?.menuId,
          label: menu?.menuName,
          isChecked: menu?.isCheckedId,
        });
      } else {
        acc[String(menu?.parentId)] = {
          value: menu?.parentId,
          label: "",
          isChecked: false,
          isAccordianOpen: false,
          isAtleastOneSubMenuSelected: menu?.isCheckedId,
          subMenu: [
            {
              value: menu?.menuId,
              label: menu?.menuName,
              isChecked: menu?.isCheckedId,
            },
          ],
        };
      }
    }

    return acc;
  },
  initialObj
);

// export const modifiedData3 = response.data.rolePermissions.reduce(
//   (acc, menu) => {
//     if()
//     return acc;
//   },
//   initialObj
// );
// interface MenuItem {
//   menuId: number;
//   parentId: number;
//   menuName: string;
//   isCheckedId: boolean;
//   expanded: boolean;
// }

// interface MenuNode {
//   value: number;
//   label: string;
//   isChecked: boolean;
//   isAccordianOpen: boolean;
//   isAtleastOneSubMenuSelected: boolean;
//   submenu: { [key: number]: MenuNode };
// }
import { response as resObj } from "./responseObject";
export const buildMenuTree = (
  menuArray: AnyObject[],
  options: {
    menuId: string;
    menuName: string;
    parentId: string;
    isChecked: string;
    isExpanded: string;
  }
) => {
  const menuMap = new Map();
  const menuTreeArray: AnyObject = {};

  menuArray?.forEach((menu) => {
    const {
      [options.menuId]: menuId,
      [options.menuName]: menuName,
      [options.isChecked]: isChecked,
      [options.isExpanded]: isExpanded,
      [options.parentId]: parentId,
    } = menu;

    const newMenu: AnyObject = {
      value: menuId,
      label: menuName,
      isChecked: isChecked,
      isAccordianOpen: isExpanded,
      isAtleastOneSubMenuSelected: false,
      parentId: parentId,
      subMenu: {},
    };

    menuMap.set(String(menuId), newMenu);
  });

  menuArray?.forEach((menu) => {
    const { [options.menuId]: menuId, [options.parentId]: parentId } = menu;
    const currentMenu = menuMap.get(String(menuId));

    if (parentId === 0) {
      menuTreeArray[String(menuId)] = currentMenu!;
    } else {
      const parentMenu = menuMap.get(String(parentId));

      if (parentMenu) {
        parentMenu.subMenu[String(menuId)] = currentMenu!;
      }
    }
  });

  return { menuTreeArray, menuMap };
};

// const menu4 = [
//   {
//     menuId: 1,
//     menuName: "Admin",
//     parentId: 0,
//     isCheckedId: false,
//     expanded: true,
//   },
//   {
//     menuId: 2,
//     menuName: "User Management",
//     parentId: 1,
//     isCheckedId: false,
//     expanded: true,
//   },
//   {
//     menuId: 3,
//     menuName: "Roles",
//     parentId: 1,
//     isCheckedId: false,
//     expanded: true,
//   },
//   {
//     menuId: 4,
//     menuName: "Permissions",
//     parentId: 2,
//     isCheckedId: false,
//     expanded: true,
//   },
//   {
//     menuId: 5,
//     menuName: "Edit User",
//     parentId: 4,
//     isCheckedId: false,
//     expanded: true,
//   },
//   {
//     menuId: 6,
//     menuName: "Add User",
//     parentId: 4,
//     isCheckedId: false,
//     expanded: true,
//   },
//   {
//     menuId: 7,
//     menuName: "Delete User",
//     parentId: 4,
//     isCheckedId: false,
//     expanded: true,
//   },
//   {
//     menuId: 8,
//     menuName: "Edit Role",
//     parentId: 3,
//     isCheckedId: false,
//     expanded: true,
//   },
//   {
//     menuId: 9,
//     menuName: "Add Role",
//     parentId: 3,
//     isCheckedId: false,
//     expanded: true,
//   },
//   {
//     menuId: 10,
//     menuName: "Delete Role",
//     parentId: 3,
//     isCheckedId: false,
//     expanded: true,
//   },
// ];
export const menu3 = buildMenuTree(response2.data.rolePermissions, {
  menuId: "menuId",
  parentId: "parentId",
  isChecked: "isCheckedId",
  isExpanded: "expanded",
  menuName: "menuName",
});

// export const menu4 = buildMenuTree4(menuData);
export const menu5 = buildMenuTree(resObj.data, {
  menuId: "id",
  parentId: "parentId",
  isChecked: "isChecked",
  isExpanded: "isExpanded",
  menuName: "name",
});

// console.log(JSON.stringify(menu3, null, 3), "000000000000000000000000000000");
// console.log(JSON.stringify(menu3, null, 5), "33333333333333");
console.log(menu3, "33333333333333");
console.log(menu5, "55555555555555");
